version: "3.2"
services:
  consul:
    command: -server -bootstrap -rejoin 
    image: progrium/consul:latest
  micro:
    command: --registry=consul --registry_address=consul:8500 api --handler=http --namespace senonerk.sup.api
    image: microhq/micro:latest
    links:
      - consul
      - auth_api
    ports:
      - "8080:8080"
  auth_api:
    build: ./api/auth
    command: --registry=consul --registry_address=consul:8500
    links:
      - consul
      - auth_srv
  auth_srv:
    build: ./srv/auth
    command: --registry=consul --registry_address=consul:8500
    links:
      - consul
      - authdb
    environment:
      DB_HOST: authdb
      DB_NAME: auth
      DB_USER: root
      DB_PASSWORD: secret
      JWT_SECRET: supersecret
      PASSWORD_HMAC_SECRET: ultrasecret
  authdb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - "authdb:/data/db"
  explorer:
    command: --registry=consul --registry_address=consul:8500 web
    image: microhq/micro:latest
    links:
      - consul
      - auth_srv
    ports:
      - "8082:8082"
volumes:
  authdb: